version: "3"
services:
  mi-scale:
    build: ../../
    security_opt:
      - no-new-privileges:true
    read_only: true
    # privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./xiaomi_mi_scale_options.json:/data/options.json:ro
      - /var/run/dbus/:/var/run/dbus/:ro #needed for bleak
    networks:
      mqtt:

  mosquitto:
    image: docker.io/library/eclipse-mosquitto:2.0.22@sha256:914f529386804c8278a4e581526b9be5e1604df44b30daabc70aa97dcefe5268
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf:rw"
    networks:
      mqtt:

networks:
  mqtt:
