---
name: 🐍 Run PyTests
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
      - master
    paths:
      - "**.py"
      - tests
      - source
      - "*requirements*.txt"
      - "**poetry.lock"
      - "**pyproject.toml"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  run_tests:
    name: 🐍 Run PyTests
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Check Out Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: 📦 Install Poetry
        run: pipx install poetry
      - name: 🔍 Extract Python version from pyproject.toml
        id: python_version
        run: |
          PYTHON_VERSION=$(grep -E '^python\s*=' pyproject.toml | sed -E 's/.*"\^?([0-9]+\.[0-9]+).*/\1/')
          echo "Detected Python version: $PYTHON_VERSION"
          echo "python-version=$PYTHON_VERSION" >> "$GITHUB_OUTPUT"
      - name: 🐍 Set Up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ steps.python_version.outputs.python-version }}
          cache: "poetry"
      - name: 📥 Install Dependencies
        run: poetry install --no-interaction --no-root
      - name: ✅ Run Tests
        run: poetry run pytest
